server:
  port: 8080

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: inventoryApp

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

#    
#    332903213848-9kopg693088vhkbdoe8pq5sev7ph01lt.apps.googleusercontent.com
#    eInr1vd2qGswrUnF5ji4eKzs